window.jQuery = window.$ = $;
window.d3 = d3;
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
const hyphyVision = require('hyphy-vision');
require('phylotree.css');
require('hyphy-vision.css');
window.absrel = hyphyVision.absrel;
window.busted = hyphyVision.busted;
window.fade = hyphyVision.fade;
window.fel = hyphyVision.fel;
window.fubar = hyphyVision.fubar;
window.gard = hyphyVision.gard;
window.meme = hyphyVision.meme;
window.relax = hyphyVision.relax;
window.slac = hyphyVision.slac;
window.bgm = hyphyVision.bgm;
window.render_branch_selection = hyphyVision.render_branch_selection ;
