os: osx
# No version of Python is available via virtualenv on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
language: generic

env:
  - TOX_ENV=py27-first_startup
  - TOX_ENV=py35-first_startup

install:
  - set -e
  - pip install tox
  - |
    if [ "$TOX_ENV" == "py27-first_startup" ]; then
        sh scripts/common_startup.sh
        wget -q https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
        mv db_gx_rev_0127.sqlite database/universe.sqlite
        sh manage_db.sh upgrade
    elif [ "$TOX_ENV" == "py35-first_startup" ]; then
        MINICONDA_URL="https://repo.anaconda.com/miniconda"
        MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
        curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
        bash $MINICONDA_FILE -b
        ~/miniconda3/bin/conda create --yes --override-channels --channel conda-forge --channel defaults --name _galaxy_ 'python=3.5' 'pip>=9' 'virtualenv>=16'
        . ~/miniconda3/bin/activate _galaxy_
    fi

script: tox -e $TOX_ENV

notifications:
  email: false
